apiVersion: v1
kind: Pod
metadata:
  label: dask
spec:
  restartPolicy: Never
  containers:
  - image: ulissigroup/kubeflow_vasp:amptorch
    imagePullPolicy: Always
    args: [dask-worker, --nthreads, '1', --no-dashboard, --memory-limit, 2GB, --death-timeout, '60']
    name: dask
    env:
    - name: PYTHONPATH
      value: "/home/jovyan/data/vasp-interactive-test:/home/jovyan/data/vasp-interactive-test/examples"
    - name: ASE_VASP_COMMAND
      value: "mpirun -np 4 --mca btl_vader_single_copy_mechanism none /opt/vasp.6.1.2_pgi_mkl/bin/vasp_gam"
    resources:
      limits:
        cpu: "4"
        memory: 2Gi
      requests:
        cpu: "4"
        memory: 2Gi
    volumeMounts:
      - mountPath: /home/jovyan/data
        name: data-vol
      - mountPath: /tmp
        name: scratch-vol
  imagePullSecrets:
  - name: ulissigroup-dockerhub
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: data
    - name: scratch-vol
      persistentVolumeClaim:
        claimName: scratch
