apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-vp
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: vp-test
        image: ulissigroup/kubeflow_vasp:beef_vdw
        ports:
        - containerPort: 80
        env:
        - name: "PPP"
          value: "SSSXCV"

