# Simple manual action that only for the purpose of status badge
name: Cori KNL

on:
  workflow_dispatch:
    inputs:
      signal:
        description: "Manual setting for the action status"
        required: true
        default: true

jobs:
  basic:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Job output
      run: |
      	echo "The slurm job id is " ${{ github.event.inputs.jobid }}
	      echo "Job was executed in " ${{ github.event.inputs.path }}
    - name: Manual succeed or fail
      run: |
        echo SIGNAL is ${{ github.event.inputs.signal }}
        if [[ ${{ github.event.inputs.signal }} != "true" ]]; then exit 1; fi
