# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package installation and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  basic:
    runs-on: ubuntu-latest
    container:
      image: ulissigroup/vasp:jovyan_base
      env: 
        VASP_COMMAND: "mpirun -np 1 --mca btl_vader_single_copy_mechanism none --mca mpi_cuda_support 0 --allow-run-as-root /opt/vasp.6.1.2_pgi_mkl_beef/bin/vasp_gam"
      options: --user root --entrypoint /bin/bash
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        

    steps:
    - name: check env
      run: |
        echo "${{ github.workspace }}"
    - uses: actions/checkout@v2
    - name: setup conda version
      run: |
        conda create --name actions -c conda-forge \
          python=${{ matrix.python-version }} pip flake8 pytest
        conda init bash
        source activate actions
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Package install
      run: |
        python -m pip install --upgrade .
    - name: Test with pytest
      run: |
        python -m pytest -s tests/
